# Generated by Django 5.0.1 on 2024-02-04 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=1000, verbose_name="ICD-10 Category"),
                ),
            ],
            options={
                "verbose_name_plural": "ICD-10 categories",
            },
        ),
        migrations.CreateModel(
            name="ICD10",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icd10_code",
                    models.CharField(max_length=3, verbose_name="ICD-10 Code"),
                ),
                (
                    "diagnosis",
                    models.CharField(max_length=1000, verbose_name="ICD-10 Diagnosis"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="icd10_api.category",
                    ),
                ),
            ],
        ),
    ]
